version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "15"

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "prettier"
enabled = true